# Generated by Django 5.0.4 on 2024-04-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id_empaque', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad_empaque', models.IntegerField()),
                ('cantidad_gastada', models.IntegerField()),
            ],
            options={
                'db_table': 'empaque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoParte',
            fields=[
                ('id_pedido_par', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.IntegerField()),
                ('cantidad_cajas', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'pedido parte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_transporte', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=11)),
                ('contenido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('rol_usuario', models.CharField(max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
