# Generated by Django 5.0.4 on 2024-05-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecaControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True},
        ),
    ]
